# Generated by Django 4.2.7 on 2023-11-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('camera', models.CharField(max_length=200)),
                ('violation', models.CharField(max_length=200)),
            ],
        ),
    ]
