version: '3.8'

services:
  django:
    container_name: django-yolo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # devices:
    #   - /dev/video0  # Add this line to pass the webcam device
    build: 
      context: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000

    environment:
      - DEBUG=1
      - SECRET_KEY=0204fo3034
      - ALLOWED_HOSTS=localhost,127.0.0.1

